routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['admin'])->group(function () {
    Route::name('admin.')->group(function () {
        Route::prefix('admin')->group(function () {

            Route::get('/', 'PageController@dashboard')->name('dashboard');
            Route::put('/update', 'UserController@updateAdmin')->name('update');

            Route::resource('categories', 'CategoryController', [
                'except' => [
                    'create',
                    'edit',
                    'show'
                ]
            ]);
            Route::resource('posts', 'PostController', [
                'except' => [
                    'create',
                    'edit'
                ]
            ]);

            Route::resource('translations', 'TranslationController', [
                'except' => [
                    'create',
                    'edit',
                    'show'
                ]
            ]);

            Route::get('/users', 'UserController@index')->name('users.index');

            Route::delete('/comments/{id}', 'CommentController@destroy')->name('comments.destroy');
        });
    });
});

Route::middleware(['categories'])->group(function () {

    Route::get('/', 'PageController@index')->name('home');

    Route::get('/categories/{id}/posts', 'CategoryController@posts')->name('category.posts');

    Route::get('/posts/{id}', 'PostController@show')->name('posts.show');
    Route::post('/posts/{pid}/comments', 'CommentController@store')->name('post.comments.store');

    Route::get('/profile', 'PageController@profile')->name('profile');

    Route::put('/users', 'UserController@update')->name('users.update');
});

Route::prefix('json')->group(function () {
    Route::get('/posts/{id}', 'PostController@jsonShow');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'slug', 'parent_id'];
    protected $with = ['parent'];

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function hasParent()
    {
        return $this->parent_id !== null;
    }

    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function hasChildren()
    {
        return $this->children()->get()->isNotEmpty();
    }

    public static function collection()
    {
        return self::all();
    }

    public static function roots($withChildren = false)
    {
        $result = self::where('parent_id', null);
        if ($withChildren) {
            return $result->with('children')->get();
        }
        return $result->get();
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public static function translationCategory()
    {
        return self::where(
            'name',
            config('constants.categories')[1]
        )->first();
    }
}

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'category_id',
        'publication_id',
        'user_id',
        'title',
        'author',
        'content'
    ];

    protected $with = ['category', 'publication'];
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function publication()
    {
        return $this->belongsTo(Publication::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function getPostedByAttribute()
    {
        return $this->author;
    }

    public function getDateAttribute()
    {
        return Carbon::parse($this->created_at)->format('d/m/y H:i:s');
    }

    public static function collection()
    {
        return self::all();
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Translation;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index()
    {
        if (user()->isAdmin()) {
            $categories = Category::collection();
            $roots = Category::roots(true);
            return view('admin.categories.index', compact('categories', 'roots'));
        }
    }

    public function store()
    {
//        TODO check if user is admin
        $rules = [
            'name' => 'required',
            'parent' => 'numeric'
        ];

//        TODO should refactor
        if (request('parent') !== '0') {
            $rules['parent'] .= '|exists:categories,id';
            $parent = request('parent');
        } else {
            $parent = null;
        }

        $this->validate(request(), $rules);

        $name = request('name');
        user()->createCategory($name, $parent);

        return redirect()->route('admin.categories.index');
    }

//    TODO replace category to id
    public function update($id)
    {
//        TODO check if user is admin
        $rules = [
            'name' => 'required'
        ];
        $this->validate(request(), $rules);

        user()->updateCategory($id, request('name'));

        return redirect()->route('admin.categories.index');
    }

//    TODO replace category to id
    public function destroy($id)
    {
        user()->removeCategory($id);

        return redirect()->route('admin.categories.index');
    }

    public function posts($id)
    {
        $category = Category::find($id);
        $posts = $category->posts;

        return view('categories.posts', compact('category', 'posts'));
    }
}

resources/views/categories/index.blade.php
<div class="container">
    <div class="row grid d-flex justify-content-center">
        @foreach($categories as $category)
            <div class="col-sm-3">
                <div class="card text-white">
                    <img class="card-img" src="{{ url('storage/images/' . $category->slug . '.jpg') }}" alt="Card image">
                    <a href="{{ route('category.posts', $category->id) }}">
                        <div class="card-img-overlay d-flex align-items-center justify-content-center">
                            <h2 class="card-title">{{ $category->name }}</h2>
                        </div>
                    </a>
                </div>
            </div>
        @endforeach
    </div>
</div>

resources/views/categories/posts.blade.php
@extends('layouts.app')

@section('title')
    {{ $category->name }}
@endsection

@section('content')
    <div class="with-bg-img" style="background: url({{ url('storage/images/' . $category->slug . '.jpg') }});"></div>
    <div class="container posts">
        <div class="card post">
            <div class="card-body">
                <h2 class="text-center">{{ $category->name }}</h2>
            </div>
        </div>

        @foreach($posts as $post)
            <div class="card post">
                <div class="card-body">
                    <h5 class="card-title"><a href="{{ route('posts.show', $post->id) }}">{{ $post->title }}</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ __('main.author') }}: {{ $post->postedBy }}</h6>
                    <p class="card-text table-responsive">
                        {!! substrTextOnly($post->content, 100) !!}
                    </p>
                    <a href="{{ route('posts.show', $post->id) }}"> {{ __('main.read_more') }}</a>
                    <p class="text-right"><small class="text-muted">{{ $post->date }}</small></p>
                </div>
            </div>
        @endforeach
    </div>
@endsection