routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['admin'])->group(function () {
    Route::name('admin.')->group(function () {
        Route::prefix('admin')->group(function () {

            Route::get('/', 'PageController@dashboard')->name('dashboard');
            Route::put('/update', 'UserController@updateAdmin')->name('update');

            Route::resource('categories', 'CategoryController', [
                'except' => [
                    'create',
                    'edit',
                    'show'
                ]
            ]);
            Route::resource('posts', 'PostController', [
                'except' => [
                    'create',
                    'edit'
                ]
            ]);

            Route::resource('translations', 'TranslationController', [
                'except' => [
                    'create',
                    'edit',
                    'show'
                ]
            ]);

            Route::get('/users', 'UserController@index')->name('users.index');

            Route::delete('/comments/{id}', 'CommentController@destroy')->name('comments.destroy');
        });
    });
});

Route::middleware(['categories'])->group(function () {

    Route::get('/', 'PageController@index')->name('home');

    Route::get('/categories/{id}/posts', 'CategoryController@posts')->name('category.posts');

    Route::get('/posts/{id}', 'PostController@show')->name('posts.show');
    Route::post('/posts/{pid}/comments', 'CommentController@store')->name('post.comments.store');

    Route::get('/profile', 'PageController@profile')->name('profile');

    Route::put('/users', 'UserController@update')->name('users.update');
});

Route::prefix('json')->group(function () {
    Route::get('/posts/{id}', 'PostController@jsonShow');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'slug', 'parent_id'];
    protected $with = ['parent'];

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function hasParent()
    {
        return $this->parent_id !== null;
    }

    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function hasChildren()
    {
        return $this->children()->get()->isNotEmpty();
    }

    public static function collection()
    {
        return self::all();
    }

    public static function roots($withChildren = false)
    {
        $result = self::where('parent_id', null);
        if ($withChildren) {
            return $result->with('children')->get();
        }
        return $result->get();
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public static function translationCategory()
    {
        return self::where(
            'name',
            config('constants.categories')[1]
        )->first();
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Translation;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index()
    {
        if (user()->isAdmin()) {
            $categories = Category::collection();
            $roots = Category::roots(true);
            return view('admin.categories.index', compact('categories', 'roots'));
        }
    }

    public function store()
    {
//        TODO check if user is admin
        $rules = [
            'name' => 'required',
            'parent' => 'numeric'
        ];

//        TODO should refactor
        if (request('parent') !== '0') {
            $rules['parent'] .= '|exists:categories,id';
            $parent = request('parent');
        } else {
            $parent = null;
        }

        $this->validate(request(), $rules);

        $name = request('name');
        user()->createCategory($name, $parent);

        return redirect()->route('admin.categories.index');
    }

//    TODO replace category to id
    public function update($id)
    {
//        TODO check if user is admin
        $rules = [
            'name' => 'required'
        ];
        $this->validate(request(), $rules);

        user()->updateCategory($id, request('name'));

        return redirect()->route('admin.categories.index');
    }

//    TODO replace category to id
    public function destroy($id)
    {
        user()->removeCategory($id);

        return redirect()->route('admin.categories.index');
    }

    public function posts($id)
    {
        $category = Category::find($id);
        $posts = $category->posts;

        return view('categories.posts', compact('category', 'posts'));
    }
}

resources/views/admin/categories/partials/form.blade.php
<form action="{{isset($action) ? $action : null}}" method="post">
    <div class="form-group">
        <label for="name">{{ __('main.naming') }}</label>
        <input type="text" class="form-control" id="name" name="name">
    </div>
    @if( $type === config('constants.types.forms.add') )
        <div class="form-group">
            <label for="parent">{{ __('main.category') }}</label>
            <select name="parent" id="parent" class="form-control">
                <option value="0">{{ __('main.non_category') }}</option>
                @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
            </select>
        </div>
    @endif
    <button type="submit" class="btn btn-primary">{{ __('main.save') }}</button>
    {{csrf_field()}}
    @if( $type === config('constants.types.forms.edit') )
        {{method_field('put')}}
    @endif
</form>

resources/views/admin/categories/partials/nodes.blade.php
<li class="d-flex justify-content-between">
    {{ $category->name }}
    <div class="d-flex justify-content-between">
        <form action="{{ route('admin.categories.destroy', $category->id) }}" method="post">
            {{ csrf_field() }}
            {{ method_field('delete') }}
            <button class="btn btn-danger">
                <span class="oi oi-x" title="Өшіру" aria-hidden="true"></span>
            </button>
        </form>
        <a class="btn btn-primary" data-toggle="modal" data-target="#editModal"
           data-name="{{ $category->name }}" data-action="{{ route('admin.categories.update', $category->id) }}">
            <span class="oi oi-pencil" title="Өзгерту" aria-hidden="true"></span>
        </a>
    </div>
</li>

@if($category->hasChildren())
    <ul>
        @foreach($category->children as $category)
            @include('admin.categories.partials.nodes', $category)
        @endforeach
    </ul>
@endif